# Generated by Django 4.1.5 on 2023-01-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Code",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("File_type", models.CharField(max_length=10)),
                ("Actual_Code", models.CharField(max_length=5000)),
            ],
        ),
    ]
