/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>About | Not Equal To (!=)</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="pt-36 bg-black" >
        <div className="w-2/5">
          <h1 className="text-7xl pb-10 text-[#0CCF89]">
            Not Equal To: <br/><span className="text-[#3EB0AC]">AI Interview Help</span>
          </h1>
          <div className="text-xl   py-10  tracking-wide text-white">
          An incredibly useful, AI powered tool for taking or preparing for interview rounds.
          We got you covered, snap a pic and run it through. Faster, and safer with Web3.
          </div>
          <div className="flex pt-10 justify-between">
            <div className=" w-[40%] text-2xl text-center rounded-full border-2 border-[#0CCF89] bg-[#0CCF89] py-6 px-12 cursor-pointer hover:bg-transparent hover:text-[#0CCF89] ">SignUp</div>
            <div className=" w-[40%] text-2xl py-6 px-12 text-center rounded-full border-2 text-[#0CCF89] border-[#0CCF89] cursor-pointer hover:bg-[#0CCF89] hover:text-black ">Learn More</div>
          </div>
          <br></br>
          <br></br>
        </div>
        
        <img src='./circles.png' alt="Ellipse16" className='absolute top-2 right-24 ' width={750} />
        
      </div>
    </div>
  )
}
